name: Schematic PDF Creation
on: [push]
jobs:
  Create-Schematic-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Kicad PDF
        uses: emilymclean/kicad-pdf@v1.0.4
        with:
          input-files: BB-STM32 Dev Board.kicad_sch
          output-file: BB-STM32WL Dev Board Schematic.pdf
